# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowing', models.FloatField(max_length=250)),
                ('age', models.FloatField(max_length=250)),
                ('memory', models.FloatField(max_length=250)),
                ('interpretation', models.FloatField(max_length=250)),
                ('muffled', models.FloatField(max_length=250)),
                ('behaviour', models.FloatField(max_length=250)),
                ('visual', models.FloatField(max_length=250)),
                ('chances', models.FloatField(max_length=250)),
            ],
        ),
    ]
