# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_undata2'),
    ]

    operations = [
        migrations.AddField(
            model_name='undata2',
            name='flag',
            field=models.IntegerField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
