# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_undata2_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undata2',
            name='flag',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
