# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0006_myuser_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
