# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0007_auto_20180327_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
