# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-28 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0011_auto_20180328_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pid',
        ),
    ]
