# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-28 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0015_auto_20180328_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='data1',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyze.Patient'),
        ),
    ]
